# Generated by Django 3.0.2 on 2020-01-20 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, verbose_name='Фамилия пользователя')),
                ('last_name', models.CharField(max_length=256, verbose_name='Имя пользователя')),
                ('email', models.CharField(max_length=256, verbose_name='Почта пользователя')),
                ('gender', models.CharField(max_length=256, verbose_name='Пол пользователя')),
                ('ip_address', models.CharField(max_length=256, verbose_name='IP пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistic.User')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('page_views', models.IntegerField()),
                ('clicks', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистики',
            },
        ),
    ]
